In [2]:
import numpy as np
import pandas as pd

from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import accuracy_score

import string
import warnings
import missingno
warnings.filterwarnings('ignore')


import pandas as pd
import cufflinks as cf
import chart_studio.plotly as py
import plotly.graph_objects as go
import numpy as np
import pandas as pd
import numpy as np
from numpy.random import gamma
from numpy.random import multivariate_normal
# from scipy.stats import multivariate_t
from scipy.stats import f
import matplotlib.pyplot as plt



cf.go_offline(connected = True)


import pandas as pd
import cufflinks as cf
import chart_studio.plotly as py
import plotly.graph_objects as go
import numpy as np
import pandas as pd
import numpy as np
from numpy.random import gamma
from numpy.random import multivariate_normal
# from scipy.stats import multivariate_t
from scipy.stats import f
import matplotlib.pyplot as plt
import missingno


cf.go_offline(connected = True)


import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

from sklearn.linear_model import Ridge, Lasso
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_squared_log_error
from sklearn.metrics import make_scorer
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score

import numpy as np
import pandas as pd
from sklearn.metrics import make_scorer
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from xgboost import XGBRegressor 
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Lasso
from sklearn.model_selection import GridSearchCV
import string
import warnings
import missingno

from IPython.core.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))

D:\anaconda\lib\site-packages\statsmodels\tools\_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


In [4]:
# train_importance = pd.read_csv('물품_train_importance_1.csv',encoding ='cp949').iloc[:,1:]
# test_importance = pd.read_csv('물품_test_importance_1.csv',encoding ='cp949').iloc[:,1:]
# test_answer = pd.read_csv('물품_y_test.csv',encoding = 'cp949').iloc[:,1:]
# train_answer = pd.read_csv('물품_y_train_1.csv',encoding ='cp949').iloc[:,1:]

In [108]:
# test_answer

In [70]:
train_importance.columns.tolist()

['낙찰자결정방법_수의',
 '낙찰자결정방법_중기간 경쟁물품 계약이행능력심사',
 '낙찰자결정방법_최저가낙찰자결정',
 '입찰계약방법_수의(총액)',
 '입찰계약방법_일반(총액)',
 '입찰계약방법_지명(총액)',
 '입찰공고차수',
 '지역제한내용_N',
 '지역제한내용_Y',
 '합계수량',
 'day',
 'month',
 'year',
 'hour',
 'dow',
 'woy']

In [71]:
import pandas as pd
import numpy as np # 각 모델에서 내부적으로 관련 라이브러리 사용 가능

from sklearn.model_selection import cross_val_score
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import RandomizedSearchCV
from scipy import stats

from sklearn.neighbors import KNeighborsRegressor         # 1. K-Nearest Neighbor(KNN)

from sklearn.tree import DecisionTreeRegressor                   # 4. Decision Tree
from sklearn.ensemble import RandomForestRegressor   # 5. Random Forest
from sklearn.ensemble import ExtraTreesRegressor             # 6. Extra Tree
from sklearn.ensemble import GradientBoostingRegressor  # 7. GBM

from xgboost import XGBRFRegressor                                     # 9. XGBoost
from lightgbm import LGBMRegressor                                 # 10. LightGBM
import warnings

warnings.filterwarnings('ignore')

In [72]:
learning_rate = [0.01, 0.05, 0.1, 0.2]
n_estimators = [100, 1000, 2000]
max_depth = [3, 5, 10, 15]

hyperparams = {
    'learning_rate': learning_rate, 
    'n_estimators': n_estimators, 
    'max_depth': max_depth
}

gd=GridSearchCV(
    estimator = GradientBoostingRegressor(random_state=1), 
    param_grid = hyperparams, 
    verbose=True, 
    cv=5, 
    scoring = "r2", 
    n_jobs=-1
)

gd.fit(train_importance, train_answer)
print(gd.best_score_)
print(gd.best_params_)

Fitting 5 folds for each of 48 candidates, totalling 240 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 12 concurrent workers.
[Parallel(n_jobs=-1)]: Done  26 tasks      | elapsed:    8.8s
[Parallel(n_jobs=-1)]: Done 176 tasks      | elapsed:  1.2min
[Parallel(n_jobs=-1)]: Done 240 out of 240 | elapsed:  1.7min finished


0.060906624050388845
{'learning_rate': 0.01, 'max_depth': 3, 'n_estimators': 100}


In [73]:
gd_1 = gd.best_estimator_

In [77]:
gd_1.predict(train_importance)

array([2.58915752e+08, 2.63703636e+08, 2.63703636e+08, ...,
       9.43917244e+08, 7.95898365e+08, 8.71010781e+08])

In [74]:
score = make_scorer(mean_squared_log_error)

# print('mean_squared_log_error = ', score(gd_1, train_importance, train_answer))


score = make_scorer(r2_score)

print('r2_score = ', score(gd_1, train_importance, train_answer))

r2_score =  0.06081832117306174


In [75]:
# test_importance

In [76]:
score = make_scorer(mean_squared_log_error)

# print('mean_squared_log_error = ', score(gd_1, test_importance, test_answer))


score = make_scorer(r2_score)

print('r2_score = ', score(gd_1, test_importance, test_answer))

NameError: name 'test_importance' is not defined

In [78]:
import joblib

joblib.dump(gd_1, 'GradientBoostingRegressor.pkl')

['GradientBoostingRegressor.pkl']

In [79]:
import numpy as np
from xgboost import XGBClassifier
from bayes_opt import BayesianOptimization
from sklearn.model_selection import cross_val_score

pbounds = {  
    'learning_rate': (0.01, 0.5),  
    'n_estimators': (100, 1000), 
    'max_depth': (3, 10),
    'min_child_weight': (0, 10),    
    'subsample': (0.5, 1.0),
    'colsample_bytree': (0.5, 1.0)
    # 'reg_lambda': (0, 1000),
    # 'reg_alpha': (0, 1.0)
}

def lgbm_hyper_param(learning_rate, n_estimators, max_depth, min_child_weight, subsample, colsample_bytree):
    max_depth = int(max_depth)
    n_estimators = int(n_estimators)
    clf = LGBMRegressor(
        boosting_type='gbdt',
        max_depth=max_depth,
        min_child_weight=min_child_weight,
        learning_rate=learning_rate, 
        n_estimators=n_estimators, 
        subsample=subsample, 
        colsample_bytree=colsample_bytree,
        random_state=1,
        device = 'gpu'
        # reg_lambda=reg_lambda,        
        # reg_alpha=reg_alpha
    )
    return np.mean(cross_val_score(clf, train_importance, train_answer, cv=5, scoring='neg_mean_squared_error'))   # cv 도 숫자로 작성하여, 내부적으로 (Stratified)KFold 사용함

optimizer = BayesianOptimization( f=lgbm_hyper_param, pbounds=pbounds, verbose=1, random_state=1)
optimizer.maximize(init_points=10, n_iter=100, acq='ei', xi=0.01)

|   iter    |  target   | colsam... | learni... | max_depth | min_ch... | n_esti... | subsample |
-------------------------------------------------------------------------------------------------
|  4        | -8.222e+1 |  0.5702   |  0.1071   |  8.605    |  9.683    |  382.1    |  0.8462   |
|  9        | -7.456e+1 |  0.6439   |  0.07371  |  3.136    |  6.788    |  290.5    |  0.6328   |
|  11       | -7.008e+1 |  0.5601   |  0.01     |  3.001    |  8.432    |  296.6    |  0.546    |
|  27       | -6.995e+1 |  0.9158   |  0.01361  |  3.274    |  8.078    |  181.3    |  0.8782   |


In [80]:
optimizer.max

{'target': -6.99530249677369e+17,
 'params': {'colsample_bytree': 0.9158469655822543,
  'learning_rate': 0.013607565331422433,
  'max_depth': 3.274271976473044,
  'min_child_weight': 8.07822966367889,
  'n_estimators': 181.34950130597989,
  'subsample': 0.8782155860634835}}

In [81]:
LGB_model = LGBMRegressor(
    colsample_bytree = 0.9158469655822543,
    learning_rate =  0.013607565331422433,
    max_depth = int(3.274271976473044),
    min_child_weight =  8.07822966367889,
    n_estimators = int(  181.34950130597989),
    subsample = 0.8782155860634835
)

In [82]:
LGB_model_2 = LGB_model.fit(train_importance,train_answer)

In [83]:
LGB_model_2.predict(train_importance)

array([3.42873081e+08, 3.39052350e+08, 3.39052350e+08, ...,
       1.08796416e+09, 9.86346036e+08, 1.14919570e+09])

In [84]:
# import joblib

# joblib.dump(LGB_model_2, 'LGBMRegressor.pkl')

['LGBMRegressor.pkl']

In [17]:
train_answer

추정가격
0     2.937020e+08
1     4.570300e+08
2     3.491200e+08
3     5.632000e+08
4     3.785930e+08
...            ...
2865  7.945000e+08
2866  8.250000e+07
2867  1.808800e+09
2868  5.653900e+08
2869  1.149000e+09

[2870 rows x 1 columns]

In [18]:
# LGB_model.predict(test_importance)

In [19]:
score = make_scorer(mean_squared_log_error)

# print('mean_squared_log_error = ', score(LGB_model, train_importance, train_answer))


score = make_scorer(r2_score)

print('r2_score = ', score(LGB_model, train_importance, train_answer))

r2_score =  0.08290501814173556


In [20]:
train_answer.loc[train_answer['배정예산'] <= 0,] 

KeyError: '배정예산'

In [21]:
train_importance.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2870 entries, 0 to 2869
Data columns (total 15 columns):
 #   Column                     Non-Null Count  Dtype  
---  ------                     --------------  -----  
 0   낙찰자결정방법_수의                 2870 non-null   int64  
 1   낙찰자결정방법_중기간 경쟁물품 계약이행능력심사  2870 non-null   int64  
 2   낙찰자결정방법_최저가낙찰자결정           2870 non-null   int64  
 3   입찰계약방법_수의(총액)              2870 non-null   int64  
 4   입찰계약방법_일반(총액)              2870 non-null   int64  
 5   입찰계약방법_지명(총액)              2870 non-null   int64  
 6   지역제한내용_N                   2870 non-null   int64  
 7   지역제한내용_Y                   2870 non-null   int64  
 8   합계수량                       2870 non-null   float64
 9   day                        2870 non-null   int64  
 10  month                      2870 non-null   int64  
 11  year                       2870 non-null   int64  
 12  hour                       2870 non-null   int64  
 13  dow                        2870 non-null   int64

In [22]:
train_answer.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2870 entries, 0 to 2869
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   추정가격    2870 non-null   float64
dtypes: float64(1)
memory usage: 22.5 KB


In [23]:
.train_answer['배정예산'].ravel()

SyntaxError: invalid syntax (<ipython-input-23-c5f9582bd863>, line 1)

In [85]:
from xgboost import XGBRegressor # 회귀트리 모델
from sklearn.model_selection import GridSearchCV

hyperparams = {
              'learning_rate': [0.05, 0.1, 0.15], 
              'max_depth': [4, 5],
              'min_child_weight': [3, 4, 5],
              'subsample': [0.7, 0.8],
              'colsample_bytree': [0.6, 0.7],
              'n_estimators': [250, 500],
               
              }

xgb_grid = GridSearchCV(estimator = LGBMRegressor(boosting_type='gbdt', device = 'gpu'), param_grid = hyperparams, 
                verbose=True, scoring='neg_mean_squared_error', cv=5, n_jobs=-1)

xgb_grid.fit(train_importance,train_answer['추정가격'].tolist())
print(xgb_grid.best_params_)

Fitting 5 folds for each of 144 candidates, totalling 720 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 12 concurrent workers.
[Parallel(n_jobs=-1)]: Done  26 tasks      | elapsed:   20.7s
[Parallel(n_jobs=-1)]: Done 176 tasks      | elapsed:  2.1min
[Parallel(n_jobs=-1)]: Done 426 tasks      | elapsed:  5.2min
[Parallel(n_jobs=-1)]: Done 720 out of 720 | elapsed:  8.9min finished


{'colsample_bytree': 0.6, 'learning_rate': 0.05, 'max_depth': 4, 'min_child_weight': 4, 'n_estimators': 250, 'subsample': 0.8}


In [86]:
xgb_grid_1 =xgb_grid.best_estimator_
xgb_grid_2 = xgb_grid_1.fit(train_importance,train_answer)

In [87]:
xgb_grid_2.predict(train_importance)

array([2.35172333e+08, 3.52698457e+08, 3.52698457e+08, ...,
       1.46505791e+09, 1.13878881e+09, 1.43175066e+09])

In [88]:
# import joblib

# joblib.dump(xgb_grid_2, 'LGBMRegressor_GridSearchCV.pkl')

['LGBMRegressor_GridSearchCV.pkl']

In [99]:
prediction = LGB_model.predict(train_importance.loc[:,train_importance.columns != '공고게시일자'])

In [104]:
prediction

array([3.42873081e+08, 3.39052350e+08, 3.39052350e+08, ...,
       1.08796416e+09, 9.86346036e+08, 1.14919570e+09])

In [100]:
score = make_scorer(mean_squared_log_error)

# print('mean_squared_log_error = ', score(xgb_grid, train_importance, train_answer))


score = make_scorer(r2_score)

print('r2_score = ', score(xgb_grid_2, train_importance, train_answer))

ValueError: Number of features of the model must match the input. Model n_features_ is 16 and input n_features is 17

In [116]:
train_answer.reset_index()[['추정가격']]

추정가격
0     2.937020e+08
1     4.570300e+08
2     3.491200e+08
3     5.632000e+08
4     3.785930e+08
...            ...
2865  7.945000e+08
2866  8.250000e+07
2867  1.808800e+09
2868  5.653900e+08
2869  1.149000e+09

[2870 rows x 1 columns]

In [114]:
train_importance.set_index()

낙찰자결정방법_수의  낙찰자결정방법_중기간 경쟁물품 계약이행능력심사  낙찰자결정방법_최저가낙찰자결정  입찰계약방법_수의(총액)  \
0           0                          0                 0              0   
1           0                          0                 0              0   
2           0                          0                 0              0   
3           0                          1                 0              0   
4           0                          0                 0              0   

   입찰계약방법_일반(총액)  입찰계약방법_지명(총액)  입찰공고차수  지역제한내용_N  지역제한내용_Y  합계수량  day  month  \
0              0              0       0         1         0   1.0   16      3   
1              0              1       0         1         0   1.0    3      1   
2              0              1       0         1         0   1.0    3      1   
3              0              0       0         1         0   1.0    5      3   
4              0              1       0         1         0   1.0   13      2   

   year  hour  dow  woy     공고게시일자  
0  2020     0    0   12 2020-03-16  
1  2020     0    4    1 2020-01-03  
2  2020     0    4    1 2020-01-03  
3  2020     0    3   10 2020-03-05  
4  2020     0    3    7 2020-02-13

In [106]:
train_importance['공고게시일자'] = [pd.to_datetime(str(i)+'-'+str(j)+'-'+str(z)) for i,j,z in zip(train_importance['year'],train_importance['month'],train_importance['day'])]

In [117]:
train_visualiztion = pd.concat([train_importance['공고게시일자'],train_answer.reset_index()[['추정가격']],pd.DataFrame(prediction,columns = ['prediction'])],axis=1)
train_visualiztion_week = train_visualiztion.groupby(pd.Grouper(key= '공고게시일자',freq = '1W')).sum()

In [118]:
train_visualiztion_week

추정가격    prediction
공고게시일자                                
2017-01-22  3.120000e+08  4.421305e+08
2017-01-29  3.098470e+08  7.971671e+08
2017-02-05  0.000000e+00  0.000000e+00
2017-02-12  1.994520e+08  5.251040e+08
2017-02-19  1.083011e+09  7.836961e+08
...                  ...           ...
2020-12-06  2.024931e+10  1.438272e+10
2020-12-13  1.764926e+10  1.424546e+10
2020-12-20  1.112809e+10  6.240058e+09
2020-12-27  1.174000e+09  9.809594e+08
2021-01-03  2.450090e+08  1.342756e+09

[207 rows x 2 columns]

In [119]:
fig = go.Figure()

fig.add_trace(go.Scatter(x = train_visualiztion_week.index, y = train_visualiztion_week['prediction'],name = 'prediction',marker_color = 'blue'))
fig.add_trace(go.Scatter(x = train_visualiztion_week.index, y = train_visualiztion_week['추정가격'],name = '실제_추정가격',marker_color = 'red'))

fig.show()

In [120]:
train_answer.index = train_importance['공고게시일자']

In [121]:
train_answer.groupby(pd.Grouper(freq = '1W')).sum()

추정가격
공고게시일자                  
2017-01-22  3.120000e+08
2017-01-29  3.098470e+08
2017-02-05  0.000000e+00
2017-02-12  1.994520e+08
2017-02-19  1.083011e+09
...                  ...
2020-12-06  2.024931e+10
2020-12-13  1.764926e+10
2020-12-20  1.112809e+10
2020-12-27  1.174000e+09
2021-01-03  2.450090e+08

[207 rows x 1 columns]

## 하나로 생각하면 성능이 좋지 않지만, 실제로는 성능이 좋다.

In [122]:
from sklearn.metrics import r2_score

r2_score(train_answer.groupby(pd.Grouper(freq = '1W')).sum(),train_visualiztion_week['prediction'])

0.5352906630397588