In [1]:
import numpy as np
import pandas as pd

from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import accuracy_score

import string
import warnings
import missingno
warnings.filterwarnings('ignore')


import pandas as pd
import cufflinks as cf
import chart_studio.plotly as py
import plotly.graph_objects as go
import numpy as np
import pandas as pd
import numpy as np
from numpy.random import gamma
from numpy.random import multivariate_normal
from scipy.stats import multivariate_t
from scipy.stats import f
import matplotlib.pyplot as plt



cf.go_offline(connected = True)


import pandas as pd
import cufflinks as cf
import chart_studio.plotly as py
import plotly.graph_objects as go
import numpy as np
import pandas as pd
import numpy as np
from numpy.random import gamma
from numpy.random import multivariate_normal
from scipy.stats import multivariate_t
from scipy.stats import f
import matplotlib.pyplot as plt
import missingno


cf.go_offline(connected = True)


import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

from sklearn.linear_model import Ridge, Lasso
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_squared_log_error
from sklearn.metrics import make_scorer
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score

import numpy as np
import pandas as pd
from sklearn.metrics import make_scorer
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from xgboost import XGBRegressor 
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Lasso
from sklearn.model_selection import GridSearchCV
import string
import warnings
import missingno
from scipy.stats import f
import scipy

from IPython.core.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))

D:\anaconda\lib\site-packages\statsmodels\tools\_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


In [2]:
df_용역 = pd.read_csv('용역_Proj_02_06.csv').iloc[:,1:]
df_공사 = pd.read_csv('공사_Proj_02_06.csv').iloc[:,1:]
df_물품 = pd.read_csv('물품_Proj_02_06.csv').iloc[:,1:]

df_용역['공고게시일자'] = pd.to_datetime(df_용역['공고게시일자'])
df_공사['공고게시일자'] = pd.to_datetime(df_공사['공고게시일자'])
df_물품['공고게시일자'] = pd.to_datetime(df_물품['공고게시일자'])

df_물품_추정가격 = df_물품.groupby(pd.Grouper(key = '공고게시일자', freq = '1W')).sum()['추정가격']
df_공사_추정가격 = df_공사.groupby(pd.Grouper(key = '공고게시일자', freq = '1W')).sum()['추정가격']
df_용역_추정가격 = df_용역.groupby(pd.Grouper(key = '공고게시일자', freq = '1W')).sum()['추정가격']

df = pd.merge(df_용역_추정가격,df_공사_추정가격,left_index= True, right_index=True, how = 'outer')
df_total_추정가격 = pd.merge(df,df_물품_추정가격,left_index= True, right_index=True , how = 'outer')

df_total_추정가격.columns = ['용역','공사','물품']

df_test = df_total_추정가격.reset_index()[['용역']].reset_index()

df_물품_ZZ = df_물품[df_물품['수요기관코드'] == 'B500001']
df_용역_ZZ = df_용역[df_용역['수요기관코드'] == 'B500001']
df_공사_ZZ = df_공사[df_공사['수요기관코드'] == 'B500001']

df_물품_ZZ_grouper = df_물품_ZZ.groupby(pd.Grouper(key = '공고게시일자', freq = '1W')).sum()[['추정가격']]
df_용역_ZZ_grouper = df_용역_ZZ.groupby(pd.Grouper(key = '공고게시일자', freq = '1W')).sum()[['추정가격']]
df_공사_ZZ_grouper = df_공사_ZZ.groupby(pd.Grouper(key = '공고게시일자', freq = '1W')).sum()[['추정가격']]

df_물품_ZZ_grouper.reset_index()[['추정가격']]
df_용역_ZZ_grouper.reset_index()[['추정가격']]
df_공사_ZZ_grouper.reset_index()[['추정가격']]

df_test = pd.merge(df_물품_ZZ_grouper.reset_index()[['추정가격']],df_용역_ZZ_grouper.reset_index()[['추정가격']],left_index = True, right_index =True, how = 'outer')
df_test_2 = pd.merge(df_test,df_용역_ZZ_grouper.reset_index()[['추정가격']],left_index = True, right_index =True, how = 'outer')

df_test.columns = ['물품','용역']
df_test_2.columns = ['물품','용역','공사']

df_test = df_test.fillna(0).copy()
df_test_2 = df_test_2.fillna(0).copy()

In [3]:
from sklearn.preprocessing import RobustScaler
from sklearn.preprocessing import robust_scale

transformer  = RobustScaler()
transformer.fit(df_test)
df_test = transformer.transform(df_test)

transformer  = RobustScaler()
transformer.fit(df_test_2)
df_test_2 = transformer.transform(df_test_2)

In [4]:
# 적절한 gamma 값 ; sklearn의 svm에서 기본 default값 계산을 참조함 (2차원)
1/ (2 *np.array(df_test).var())

0.17349953467545662

In [5]:
# 적절한 gamma 값 ; sklearn의 svm에서 기본 default값 계산을 참조함 (3차원)
1/ (2 *np.array(df_test_2).var()) 

0.15141959537014263

In [6]:
from sklearn.preprocessing import RobustScaler
from sklearn.preprocessing import robust_scale

transformer  = RobustScaler()
transformer.fit(df_test)
df_test = transformer.transform(df_test)

transformer  = RobustScaler()
transformer.fit(df_test_2)
df_test_2 = transformer.transform(df_test_2)

In [7]:
import sys
sys.path.append("C:/Users/USER/Documents/Jupyter Notebook/public_procurement/Project_02_15\SVDD-Python-master/")

## 일단 2차원(물품 / 용역) 만 보기로 하였다. 왜냐하면, 시각화 시켜서 이해하기에는 2차원이 적당하기 때문이다.

In [236]:
df_test.shape

(207, 2)

In [235]:
"""
An example for SVDD model fitting with negataive samples
"""

import numpy as np
from src.BaseSVDD import BaseSVDD

# create 100 points with 2 dimensions
# n = 100
# dim = 2
# X = np.r_[np.random.randn(n, dim)]

X = np.array(df_test)

# svdd object using rbf kernel
svdd = BaseSVDD(C=1.0, gamma=0.1, kernel='rbf', display='on')

# fit the SVDD model
svdd.fit(X,bs_size = 500 , alpha = 0.05)

# predict the label
y_predict = svdd.predict(X)

# plot the boundary
# svdd.plot_boundary(X)

# plot the distance
radius = svdd.radius_2
distance = svdd.get_distance(X)
svdd.plot_distance(radius, distance)



*** Fitting of the SVDD model is completed. ***

running time         = 0.0790 seconds
kernel function      = rbf
iterations           = 12
number of samples    = 207
number of features   = 2
number of SVs        = 12
ratio of SVs         = 5.7971 %
accuracy             = 93.2367 %




*** Prediction of the provided data is completed. ***

running time         = 0.0470 seconds
number of samples    = 207
number of alarm      = 14




## 3차원으로 실행하였을 때는 다음과 같다. 이때는 4차원으로 차원을 높이는데 시각화할 수 없으므로, SVDD 관리도 만 그리기로 하였다.

In [41]:
df_test_2

array([[-5.80382788e-01, -4.76233688e-01, -4.76233688e-01],
       [-5.81019063e-01, -4.76233688e-01, -4.76233688e-01],
       [-6.72586113e-01, -4.76233688e-01, -4.76233688e-01],
       [-6.13643364e-01, -4.76233688e-01, -4.76233688e-01],
       [-3.52530935e-01, -4.76233688e-01, -4.76233688e-01],
       [-3.52530935e-01, -4.76233688e-01, -4.76233688e-01],
       [-5.33282256e-01, -4.76233688e-01, -4.76233688e-01],
       [ 6.21783375e-01, -4.76233688e-01, -4.76233688e-01],
       [-8.59737184e-02, -4.76233688e-01, -4.76233688e-01],
       [-6.22155646e-01, -4.76233688e-01, -4.76233688e-01],
       [-5.75624860e-01, -4.76233688e-01, -4.76233688e-01],
       [-6.22155646e-01, -4.76233688e-01, -4.76233688e-01],
       [-4.49879620e-01, -4.76233688e-01, -4.76233688e-01],
       [-4.32837372e-01, -3.30052286e-01, -3.30052286e-01],
       [ 1.24541741e+00, -2.23142651e-01, -2.23142651e-01],
       [-6.72586113e-01,  1.45606767e-01,  1.45606767e-01],
       [-6.72586113e-01, -2.48639386e-01

## 모델을 만드는 과정에 이 모델을 만들 때 주어진 데이터를 얼마나 정확히 나타내는지 보여줌 (Train 데이터에 대한 모델의 성능)
## 모델을 만들고 난 다음에 prediction. 이 모델에 들어갈 새로운 데이터를 얼마나 정확하게 분류하는지 보여줌. (Test 데이터에 대한 모델의 성능)
## 똑같이 Unlabeled 된 데이터에 대해서 이 2개는 같을 수도 있으나, 처음에 predict 한 것과 그 다음에 predict 한 것의 결과는 다를 수 있으므로, accuracy에서 차이가 날 수 밖에 없다. 이때는 성능이 더 좋은 것을 택하도록 하자.

In [188]:
import sys
sys.path.append("..")
import numpy as np
from src.BaseSVDD import BaseSVDD

# create 100 points with 2 dimensions
n = 200
dim = 2
X = np.array(df_test)

# svdd object using rbf kernel
svdd = BaseSVDD(C=0.9, gamma=0.3, kernel='rbf', display='on')

# fit the SVDD model
svdd.fit(X,bs_size = 500 , alpha = 0.01) ## 모델을 만들고 난 다음에 이 모델을 만들 때 주어진 데이터를 얼마나 정확히 나타내는지 보여줌 (Train 데이터에 대한 모델의 성능)


# # predict the label
y_predict = svdd.predict(X) ## 모델을 만들고 난 다음에 이 모델에 들어갈 새로운 데이터를 얼마나 정확하게 분류하는지 보여줌. (Test 데이터에 대한 모델의 성능)

## 똑같이 Unlabeled 된 데이터에 대해서 이 2개는 같을 수도 있으나, 중간 mapping 과정 (kernel)에서 차이가 있을 수 있으므로(비모수 방법으로 분포를 추정할 때 다르게 추정되어질 수 있다) 차이가 나는 경우도 발생한다. 그러나 정확한 것은 predict이다. 

# # plot the boundary
# svdd.plot_boundary(X)

# # plot the distance
# radius = svdd.radius_2

# distance = svdd.get_distance(X)
# svdd.plot_distance(radius, distance)



*** Fitting of the SVDD model is completed. ***

running time         = 0.0890 seconds
kernel function      = rbf
iterations           = 12
number of samples    = 207
number of features   = 2
number of SVs        = 18
ratio of SVs         = 8.6957 %
accuracy             = 91.7874 %




*** Prediction of the provided data is completed. ***

running time         = 0.0480 seconds
number of samples    = 207
number of alarm      = 4




In [187]:
svdd.predict(X)



*** Prediction of the provided data is completed. ***

running time         = 0.0490 seconds
number of samples    = 207
number of alarm      = 17




matrix([[ 1.],
        [ 1.],
        [-1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [-1.],
        [ 1.],
        [ 1.],
        [-1.],
        [-1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [-1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [-1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 

In [177]:
pd.DataFrame(svdd.results['predicted_y_2']).value_counts()

 1.0    190
-1.0     17
dtype: int64

In [179]:
svdd.predict(svdd.X)



*** Prediction of the provided data is completed. ***

running time         = 0.0490 seconds
number of samples    = 207
number of alarm      = 4




matrix([[ 1.],
        [ 1.],
        [-1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 

In [169]:

"""
An example for SVDD model fitting with negataive samples
"""
import sys
sys.path.append("C:/Users/USER/Documents/Jupyter Notebook/public_procurement/Project_02_15\SVDD-Python-master/")
import numpy as np
from src.BaseSVDD import BaseSVDD

def make_radius_bootstrap(bs_size, alpha):
    
    quantile_list_d1 = []
    for _ in range(bs_size):
        samples_d1 = np.random.choice(np.array(distance).ravel(), size=100, replace=True)

        quantile_d1 = np.quantile(samples_d1, 1-alpha)

        quantile_list_d1.append(quantile_d1)
        
    radius = np.mean(quantile_list_d1)
    
    return radius



# create 100 points with 2 dimensions
# n = 100
# dim = 2
# X = np.r_[np.random.randn(n, dim)]

X = np.array(df_test_2)

# svdd object using rbf kernel
svdd = BaseSVDD(C=1.0, gamma=0.15, kernel='rbf', display='on')

# fit the SVDD model
svdd.fit(X,bs_size = 500 , alpha = 0.01)

# predict the label
y_predict = svdd.predict(X,svdd.y)

# # plot the boundary
# # svdd.plot_boundary(X)

# # # plot the distance
# # radius = svdd.radius
# distance = svdd.get_distance(X)




radius = svdd.radius_2
distance = svdd.get_distance(X)
svdd.plot_distance(radius, distance)





*** Fitting of the SVDD model is completed. ***

running time         = 0.0820 seconds
kernel function      = rbf
iterations           = 13
number of samples    = 207
number of features   = 3
number of SVs        = 17
ratio of SVs         = 8.2126 %
accuracy             = 97.1014 %




*** Prediction of the provided data is completed. ***

running time         = 0.0480 seconds
number of samples    = 207
number of alarm      = 6
accuracy             = 97.1014 %




In [125]:
svdd.solve_problem(svdd._get_kernel(X,X))

In [144]:
svdd.predict(svdd.X,svdd.y)



*** Prediction of the provided data is completed. ***

running time         = 0.0480 seconds
number of samples    = 207
number of alarm      = 4
accuracy             = 98.0676 %




matrix([[ 1.],
        [ 1.],
        [-1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 

In [95]:
b = svdd.predict(svdd.X,svdd.y)



*** Prediction of the provided data is completed. ***

running time         = 0.0490 seconds
number of samples    = 207
number of alarm      = 14
accuracy             = 93.2367 %




In [93]:
pd.DataFrame(b).value_counts()

 1.0    193
-1.0     14
dtype: int64

In [12]:
a = svdd.results

In [13]:
pd.DataFrame(a['y']).value_counts()

1.0    207
dtype: int64

In [14]:
pd.DataFrame(a['predicted_y_2']).value_counts()

 1.0    201
-1.0      6
dtype: int64

In [53]:
pd.DataFrame(a['predicted_y_2']).value_counts()

 1.0    201
-1.0      6
dtype: int64

In [15]:
1 -6/207

0.9710144927536232

In [49]:
a['exist_y']

False

In [27]:
pd.DataFrame(svdd.predicted_y_).value_counts()

 1.0    193
-1.0     14
dtype: int64

In [36]:
svdd.accuracy

0.9323671497584541

In [39]:
pd.DataFrame(svdd.predict(svdd.X,svdd.y)).value_counts()



*** Prediction of the provided data is completed. ***

running time         = 0.0520 seconds
number of samples    = 207
number of alarm      = 14
accuracy             = 93.2367 %




 1.0    193
-1.0     14
dtype: int64

In [51]:
pd.DataFrame(svdd.predicted_y_).value_counts()

 1.0    193
-1.0     14
dtype: int64

In [22]:
from sklearn.metrics import accuracy_score

accuracy_score(svdd.y, svdd.predicted_y_)

0.9323671497584541

## UCLdl Kernel 기반으로 계산되어졌다면, 이제는 Distance를 기반으로 한 Bootstrap을 사용하기로 하였다. 이렇게 하면 우리가 커널 기반으로 생성한 UCL이 적절한 alpha값을 나타내지 않음을 알 수 있다. 그러므로, bootstrap을 사용하여 우리가 설정한 alpha값을 따르도록 하였다.